version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    # Закомментируйте или удалите volume, если он мешает
    # volumes:
    #   - ./frontend:/usr/share/nginx/html:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge